package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/coilyco/sirens-echo/internal/community"
)

// The rendered prompt is the model's whole instruction surface, and it is
// assembled from several files. See docs/sirens-echo-prompt.md.
const renderedName = "rendered/prompt.txt"

var trackedDefinitions = []string{
	"agents/echo/definition.yaml",
	"agents/deep/definition.yaml",
}

// sampleHistory and sampleRequest keep the user-prompt section deterministic,
// so a snapshot diff only ever reflects a change in the harness.
var sampleHistory = []community.TranscriptEntry{
	{Author: "member", Content: "Is the server up?"},
	{Author: "coilyco", Content: "Checking now."},
}

var sampleRequest = community.TranscriptEntry{
	Author:  "member",
	Content: "What changed in the last update?",
}

// composedDefinition is the profile the baked bundles belong to.
const composedDefinition = "agents/deep/definition.yaml"

func main() {
	check := flag.Bool("check", false, "fail on a stale snapshot instead of rewriting it")
	bundles := flag.String("bundles", "", "baked bundle directory, one subdirectory per role")
	flag.Parse()

	if *bundles != "" {
		if err := checkRoleBundles(*bundles); err != nil {
			log.Fatal(err)
		}
		return
	}

	stale := make([]string, 0, len(trackedDefinitions))
	for _, path := range trackedDefinitions {
		// Beside its own definition, since every agent's file is now named
		// definition.yaml and a shared directory would collide. See #816.
		target := filepath.Join(filepath.Dir(path), renderedName)
		rendered, err := render(path)
		if err != nil {
			log.Fatalf("render %s: %v", path, err)
		}
		existing, readErr := os.ReadFile(target)
		if readErr == nil && string(existing) == rendered {
			fmt.Printf("current %s (%d bytes)\n", target, len(rendered))
			continue
		}
		if *check {
			stale = append(stale, target)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			log.Fatalf("create %s: %v", filepath.Dir(target), err)
		}
		if err := os.WriteFile(target, []byte(rendered), 0o644); err != nil {
			log.Fatalf("write %s: %v", target, err)
		}
		fmt.Printf("wrote %s (%d bytes)\n", target, len(rendered))
	}
	if len(stale) > 0 {
		log.Fatalf(
			"stale prompt snapshots: %s\nrun `just prompt-dump` and commit the result",
			strings.Join(stale, ", "),
		)
	}
}

// checkRoleBundles loads every baked bundle, which validates each role's prompt,
// so a bundle that failed to compose stops the build instead of shipping neutral.
func checkRoleBundles(bundleDir string) error {
	// Bundles are build output, so an ordinary checkout has none and the bare
	// loader error names a path rather than the step that creates it.
	if _, err := os.Stat(bundleDir); errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf(
			"no baked bundles at %s\n"+
				"  bake them first with `just compose-bundles`, or run\n"+
				"  `just role-check`, which bakes and checks in one step",
			bundleDir,
		)
	}
	definition, err := community.LoadDefinition(composedDefinition)
	if err != nil {
		return err
	}
	localPolicy, err := community.LoadSkillpack(definition.LocalSkillRoots)
	if err != nil {
		return err
	}
	loaded, err := community.LoadRoleBundles(
		bundleDir,
		definition,
		community.PlaceholderPrincipal,
		localPolicy,
	)
	if err != nil {
		return err
	}
	for _, bundle := range loaded {
		// The prompt size is the early warning issue 98 asked for. It moves with
		// upstream wording, so it is reported and never gated.
		fmt.Printf("role %s: %d skills, prompt %d bytes\n",
			bundle.Role, len(bundle.Skills), len(bundle.SystemPrompt))
	}
	return nil
}

func render(path string) (string, error) {
	definition, err := community.LoadDefinition(path)
	if err != nil {
		return "", err
	}
	localPolicy, err := community.LoadSkillpack(definition.LocalSkillRoots)
	if err != nil {
		return "", err
	}
	composed := ""
	if definition.Composed {
		composed = community.PlaceholderComposed
	}
	systemPrompt := community.BuildSystemPrompt(definition, community.PlaceholderPrincipal, composed, localPolicy)
	if err := community.ValidateSystemPrompt(definition, community.PlaceholderPrincipal, systemPrompt); err != nil {
		return "", err
	}
	prompt := community.BuildTurnPrompt(systemPrompt, sampleHistory, sampleRequest)

	var output strings.Builder
	fmt.Fprintf(&output, "Generated by `just prompt-dump`. Do not edit by hand.\n")
	fmt.Fprintf(&output, "Definition: %s\n", path)
	fmt.Fprintf(&output, "Identity: %s\n", definition.Identity)
	fmt.Fprintf(&output, "Response style: %s\n", definition.ResponseStyle)
	fmt.Fprintf(&output, "Local policy roots: %s\n", strings.Join(definition.LocalSkillRoots, ", "))
	fmt.Fprintf(&output, "Principal: placeholder, deployment owns the real values\n")
	fmt.Fprintf(&output, "System prompt bytes: %d\n", len(systemPrompt))
	fmt.Fprintf(&output, "\n===== SYSTEM PROMPT =====\n\n%s", systemPrompt)
	fmt.Fprintf(&output, "\n===== TURN CONTEXT (fixed sample) =====\n\n%s\n", prompt.Context)
	fmt.Fprintf(&output, "\n===== USER MESSAGE (fixed sample) =====\n\n%s\n", prompt.Message)
	return output.String(), nil
}
