package community

import (
	"fmt"
	"sort"
	"strings"
)

// Every enabled/disabled switch this service ships lives here, for the reason
// the numbers live in config.go. See docs/sirens-echo-tuning.md.

// FlagReferenceHeading opens the generated reference, so the writer and the
// checker cannot disagree about the first line.
const FlagReferenceHeading = "Every feature a deployment may turn on or off."

// featureFlag binds one switch, its environment name, its default, and what it
// turns on. One line each, so none of the four can drift from the others.
type featureFlag struct {
	env      string
	target   *bool
	fallback bool
	// summary is what the flag turns on, in one sentence for the reference.
	summary string
}

// featureFlags is the closed set. A switch absent from here is a switch nobody
// can enumerate, which is what TestEveryFeatureFlagLivesInTheTable refuses.
func featureFlags(cfg *Config) []featureFlag {
	return []featureFlag{
		{
			env:      "SIRENS_ECHO_DISCORD_ENABLED",
			target:   &cfg.DiscordEnabled,
			fallback: true,
			summary:  "Open the Discord gateway session at all.",
		},
		{
			env:      "SIRENS_ECHO_DISCORD_GATEWAY",
			target:   &cfg.DiscordGateway,
			fallback: true,
			summary: "Connect this process's own gateway session. Off, it posts " +
				"over REST and hears Discord only through the event queue.",
		},
		{
			env:      "SIRENS_ECHO_DISCORD_QUEUE",
			target:   &cfg.DiscordQueue,
			fallback: false,
			summary: "Take Discord events from the Postgres queue the intake " +
				"writes, and send this process's own gateway events there too.",
		},
		{
			env:      "SIRENS_ECHO_DISCORD_DM_ENABLED",
			target:   &cfg.DiscordDMEnabled,
			fallback: false,
			summary:  "Admit direct messages, which carry no guild moderation.",
		},
		{
			env:      "SIRENS_ECHO_DISCORD_COMMANDS",
			target:   &cfg.DiscordCommandsEnabled,
			fallback: false,
			summary:  "Register and serve Discord application commands.",
		},
		{
			env:      "SIRENS_ECHO_SLACK_ENABLED",
			target:   &cfg.SlackEnabled,
			fallback: false,
			summary: "Open the Slack Socket Mode session. Needs both Slack tokens " +
				"and a Slack access policy, and refuses to start without them.",
		},
		{
			env:      "SIRENS_ECHO_COALESCE_ENABLED",
			target:   &cfg.CoalesceEnabled,
			fallback: false,
			summary:  "Batch a member's rapid comments into one turn on a worker pool.",
		},
		{
			env:      "SIRENS_ECHO_THREAD_SUMMARY",
			target:   &cfg.ThreadSummary,
			fallback: false,
			summary: "End a thread turn by editing this service's first reply " +
				"there rather than posting another, so the thread carries one " +
				"living answer.",
		},
		{
			env:      "SIRENS_ECHO_JEV_DIRECT_TOOLS",
			target:   &cfg.JevDirectTools,
			fallback: false,
			summary: "Answer from a tool's own reply template, with no model call, " +
				"when route.jev picks that server and tool at 0.9 or above.",
		},
		{
			env:      "SIRENS_ECHO_MCP_REEXPORT",
			target:   &cfg.MCPReexport,
			fallback: false,
			summary: "Offer the roster's own tools over /mcp beside turn. " +
				"They bypass the turn pipeline's checks, so they require the " +
				"deployment token.",
		},
	}
}

// applyFeatureFlags reads every flag into cfg. An unparsable value is named and
// fatal rather than silently taking the default, unlike a knob.
func applyFeatureFlags(cfg *Config, lookup func(string) string) error {
	for _, flag := range featureFlags(cfg) {
		value, err := boolOrDefault(lookup(flag.env), flag.fallback)
		if err != nil {
			return fmt.Errorf("%s: %w", flag.env, err)
		}
		*flag.target = value
	}
	return nil
}

// RenderFlagReference writes the generated reference of every feature a
// deployment may turn on or off.
func RenderFlagReference() string {
	var reference Config
	rows := make([]string, 0, len(featureFlags(&reference)))
	for _, flag := range featureFlags(&reference) {
		rows = append(rows, fmt.Sprintf(
			"%-34s %-5s %s",
			strings.TrimPrefix(flag.env, "SIRENS_ECHO_"),
			boolWord(flag.fallback),
			flag.summary,
		))
	}
	sort.Strings(rows)
	return FlagReferenceHeading + "\n" +
		"Generated by `just flags`, every name prefixed SIRENS_ECHO_. The second column\n" +
		"is the default, and an unparsable value is fatal at startup rather than ignored.\n" +
		"Why the switches live where they do: docs/sirens-echo-tuning.md\n\n" +
		"NAME                               ON?   WHAT IT TURNS ON\n" +
		strings.Join(rows, "\n") + "\n"
}

func boolWord(on bool) string {
	if on {
		return "on"
	}
	return "off"
}
